### PR TITLE
More Features

### PR DESCRIPTION
**Pull request by javelinanddart**
Merge with CM
Update BFQ
Add FRANDOM
Update Sound Control
Update Simple GPU Governor
More TCP Congestion Control Algorithms'
The Intelli_Plug Kconfig Fix (rebased)
Various Optimizations
Update Intelli_Plug to version 3.9
LZ4 Support

### CODE REVIEW

**Comment by AKToronto** [comment]
Maybe I dont understand github, but why are there soooo many commits with some of my commits repeated? Im just having trouble understanding exactly what was changed and why :-( Im sure I can figure it out eventually. Right now Im working on that error all this created... Im guessing it has something to do with trying to revert the sweep to wake stuff??? which was best left untouched in my view... Im sure the rest is good stuff though!

**Comment by javelinanddart** [comment]
I'm confused as well. I only had 70 something commits I wanted to merge.....

**Comment by AKToronto** [comment]
Oh wait I figured out what needed to be changed to get it to compile!!!

**Comment by javelinanddart** [comment]
Correction: I had 56 Commits I wanted to merge for KitKat. I'm not sure why this happened. What needed to be changed?

**Comment by AKToronto** [comment]
uint8_t cmd[3] in the sensor_irq_do_work function needs to read uint8_t cmd[3] = {0,0,0};

**Comment by AKToronto** [comment]
OK im gonna test all these changes out tonight and post a merge for all to consume tomorrow if it all works out!

**Comment by javelinanddart** [comment]
It's good that you know C lol
I'm clueless xD surprised I made it this far with my kernel
Github is being weird though
Thanks!

**Pull request merged**
