### PR TITLE
Merge with CM

### PR DESCRIPTION
**Pull request by javelinanddart**
Merge with CM, Add Support for Snappy Comression and Decompression + use Snappy for ZRAM over LZO (thanks to Faux123 for the reference as to how to do it) as it's faster but leave lzo as an option. Also build exfat and scsi_wait_scan into the kernel.

### CODE REVIEW

**Comment by javelinanddart** [comment]
A further merge with CM will allow Lz4 as well

**Comment by javelinanddart** [comment]
Merged with CM
They got ZRAM with Lz4

**Comment by javelinanddart** [comment]
It's all cleaned up between my merges with CM and trying to add Snappy
Compiles very cleanly

**Comment by cannondalev2000** [comment]
lz4 is better in terms of speed. m7 is the only device in the msm8960 kernel that wouldnt have an insane amount of overhead using anything other than lz4 in zram. ville evita etc cant handle it the compression without lag unless its lz4

**Comment by josephannareddy** [comment]
Didn't know that
I've only seen ZRAM with LZ4 except in CM's kernel before @jrior001 added it

**Comment by josephannareddy** [comment]
It has LZ4 at the moment, javelinanddart cleaned up the snappy mess

**Pull request closed without merging**
