### PR TITLE
More Features

### PR DESCRIPTION
**Pull request by javelinanddart**
Added Option for @ShowP1984's MSM_MPDECISION
Intelli_Plug Kconfig Fix (now config menu between stock, showp, and intelli)
exFAT Support via Samsung's Open Source exFAT Module
Various Optimizations, and LZ4 Support
FRANDOM Support
Sound Control Updates
Minor Logic Fix with Simple GPU Governor
Better Build Flags in Makefile
Enable TCP Control Algorithms
More Undervolting
FiFo, ZEN, and Vr I/O Schedulers
Minor Compilation Fixes
Merge with Upstream CyanogenMod/CAF

### CODE REVIEW

**Comment by javelinanddart** [comment]
TRIPNDROID Was Removed for Stability Reasons, my Intelli_Plug KConfig Clean Up was flawed: if MP_DEC was chosen, Intelli_Plug would still be compiled, Issue is fixed now

**Comment by javelinanddart** [comment]
Merged with CM: Updated to Linux 3.4.105
Fixed a second derp in the Intelli_Plug Clean Up, A choice menu in Kconfig doesn't support "default n" in the choice

**Comment by javelinanddart** [comment]
Remove Undervolting even further, It's not stable

**Comment by javelinanddart** [comment]
Update Intelli_Plug to 3.9 (Add Performance Boost Option)

**Comment by javelinanddart** [comment]
Update BFQ, add Ofast Option at Compile Time

**Comment by javelinanddart** [comment]
I implemented the Fix, Merged with CM Again and I added ElementalX Governor. I also modified the IceCode installer accordingly and transferred that repo to you
I implemented the ramdisk fix in the the IceCode Installer

**Comment by AKToronto** [comment]
Cool cool. Got crazy busy with work but should look at it over the
weekend... Im also a tad worried w/ too many governors and schedulers...
they add to the size of the kernel, especially with o3 and I know there is
an upper limit i think, but I dont know what that is... Perhaps its still
fine though with the extra stuff just a matter of testing.

**Comment by javelinanddart** [comment]
Then we compile them as modules lol
We have a huge system partition (especially with cm being 200 mb and hboot2.16 having 1.5GB)
People are running this build just fine. Have you looked at the ramdisk changes I made yet?

**Comment by javelinanddart** [comment]
BTW, I hope I'm not being rude in any way by posting those test builds, I just want everyone to be on the updated builds. The new Governor Window in the AROMA Installer is working nicely with the governor script (from the cmdline.sh). I added that as a seperate.sh to make it easier to work with

**Comment by javelinanddart** [comment]
Hey, I compiled Prima with O3 on my kernel (still on kitkat) and I switched to XZ compression and the zip went down by like 3mb. I think it's a valid option to switch to xz so we don't run into the dilemma of running out of space for the kernel/boot.img

**Pull request merged**
